spring:
  profiles:
    active: dev
  session:
    store-type: none
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    cache: false
#  jpa:
#    show-sql: true
#    database: mysql
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.bolean.entity
  configuration:
    cache-enabled: true
    use-generated-keys: true
    default-executor-type: reuse
    lazy-loading-enabled: true
    default-statement-timeout: 25000
logging:
  config: classpath:log4j2.xml
---
spring:
    profiles: dev
    datasource:
       type: com.alibaba.druid.pool.DruidDataSource
       url: jdbc:mysql://localhost:3306/student?characterEncoding=utf-8
       username: root
       password:
       driver-class-name: com.mysql.jdbc.Driver
       # 初始化大小，最小，最大
       druid:
         initial-size: 5
         min-idle: 3
         max-active: 20
         max-wait: 60000
server:
  port: 8080
---
spring:
    profiles: prod
    datasource:
       type: com.alibaba.druid.pool.DruidDataSource
       platform: mysql
       url: jdbc:mysql://localhost:3306/student?characterEncoding=utf-8
       username: root
       password:
       driver-class-name: com.mysql.jdbc.Driver
       # 初始化大小，最小，最大
       druid:
         initial-size: 5
         min-idle: 3
         max-active: 20
         max-wait: 60000
server:
    port: 8081




